name: Upload to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install huggingface hub
        run: pip install huggingface_hub

      - name: Upload files to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
         huggingface-cli login --token $HF_TOKEN --add-to-git-credential

         huggingface-cli repo push . \
          --repo-id noahabebe/spellcheck \
          --commit-message "Upload model files" \
          --token $HF_TOKEN



